# Setup
title:            'State of Connecticut'
tagline:          'Race, Ethnicity, and Lanugage (REL) Standards'
description:      'Standards for REL data'

author:
  name:           'State of Connecticut'
  url:            https://ctopendata.github.io/REL-standards/

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/CTOpenData/REL-standards

# Google Analytics
google_analytics: UA-56144207-2
